# Site settings
title: Kimberly Line
logo: "/headshot3.png"

description: >
  Computer Science Student at Charleston Southern University<br />
  Bachelor of Technology in Computer Science (Expected 2026)
  <br /><br />
  <a href="https://wonderline14.github.io/resume.pdf">View My Resume</a>
  <br /><br />
  <a href="https://github.com/WonderLine14">View My GitHub Profile</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/kimberly-line/">View My LinkedIn Profile</a>
  <br /><br />
  <a href="mailto:KMLine@student.csuniv.edu">Email Me</a>

github_username: WonderLine14

theme: jekyll-theme-minimal
